"""paginate_offset / paginate_cursor and the ORM mixins, against a real SQLite database."""

from __future__ import annotations

import uuid
from collections.abc import AsyncIterator
from datetime import UTC, datetime

import pytest
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker, create_async_engine
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

from pycommon.persistence.mixins import SoftDeleteMixin, TimestampMixin, UUIDv7PrimaryKeyMixin
from pycommon.persistence.pagination import paginate_cursor, paginate_offset


class Base(DeclarativeBase):
    pass


class Item(Base, UUIDv7PrimaryKeyMixin, TimestampMixin, SoftDeleteMixin):
    __tablename__ = "items"
    name: Mapped[str] = mapped_column()


@pytest.fixture
async def session() -> AsyncIterator[AsyncSession]:
    engine = create_async_engine("sqlite+aiosqlite:///:memory:")
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)
    maker = async_sessionmaker(engine, expire_on_commit=False)
    async with maker() as s:
        yield s
    await engine.dispose()


async def _seed(session: AsyncSession, count: int) -> list[Item]:
    items = [Item(name=f"item-{i:02d}") for i in range(count)]
    session.add_all(items)
    await session.commit()
    return sorted(items, key=lambda i: i.id)


# --- mixins ---------------------------------------------------------------


async def test_uuid7_primary_key_is_assigned_on_flush(session: AsyncSession) -> None:
    """A column default, so it lands at INSERT — generated by the application,
    which means no RETURNING round trip to read it back. The attribute is None
    until then; code needing the id earlier must flush."""
    item = Item(name="x")
    assert item.id is None

    session.add(item)
    await session.flush()
    assert isinstance(item.id, uuid.UUID)
    assert item.id.version == 7


async def test_uuid7_keys_sort_in_insertion_order(session: AsyncSession) -> None:
    """The whole reason to prefer v7 over v4 — inserts land at the end of the
    index instead of scattering across it."""
    items = await _seed(session, 50)
    ids = [i.id for i in items]
    assert ids == sorted(ids)


async def test_timestamps_are_set_by_the_database(session: AsyncSession) -> None:
    item = Item(name="x")
    session.add(item)
    await session.commit()
    assert item.created_at is not None
    assert item.updated_at is not None


async def test_soft_delete_predicates_filter_correctly(session: AsyncSession) -> None:
    """No global query filter: the exclusion is visible at the call site, because
    a filter that applies itself everywhere is one people forget exists."""
    await _seed(session, 4)
    rows = list((await session.execute(select(Item))).scalars().all())
    rows[0].mark_deleted(now=datetime.now(UTC))
    await session.commit()

    active = (await session.execute(select(Item).where(Item.is_active()))).scalars().all()
    deleted = (await session.execute(select(Item).where(Item.is_deleted()))).scalars().all()
    assert len(active) == 3
    assert len(deleted) == 1


# --- offset pagination ----------------------------------------------------


async def test_offset_pagination_reports_total_and_more(session: AsyncSession) -> None:
    await _seed(session, 25)
    page = await paginate_offset(session, select(Item).order_by(Item.id), limit=10)
    assert len(page.items) == 10
    assert page.meta.total_items == 25
    assert page.meta.has_more is True
    assert page.meta.page == 1


async def test_offset_last_page_reports_no_more(session: AsyncSession) -> None:
    """has_more comes from fetching one extra row, not from comparing against the
    total — so it stays right even when the count is stale."""
    await _seed(session, 25)
    page = await paginate_offset(session, select(Item).order_by(Item.id), limit=10, offset=20)
    assert len(page.items) == 5
    assert page.meta.has_more is False


async def test_offset_can_skip_the_count_query(session: AsyncSession) -> None:
    """The count scans the whole filtered set; an infinite-scroll list never
    renders it and should not pay for it."""
    await _seed(session, 5)
    page = await paginate_offset(session, select(Item).order_by(Item.id), with_total=False)
    assert page.meta.total_items is None
    assert len(page.items) == 5


async def test_count_ignores_order_by(session: AsyncSession) -> None:
    """A count subquery carrying ORDER BY is rejected by PostgreSQL when it sorts
    on a column the count does not select."""
    await _seed(session, 3)
    page = await paginate_offset(session, select(Item).order_by(Item.name.desc()), limit=2)
    assert page.meta.total_items == 3


async def test_limit_is_clamped_and_validated(session: AsyncSession) -> None:
    """limit arrives from a query string; unbounded, it asks the database for the
    whole table."""
    await _seed(session, 3)
    page = await paginate_offset(session, select(Item), limit=10_000, max_limit=50)
    assert page.meta.limit == 50

    with pytest.raises(ValueError, match="limit must be"):
        await paginate_offset(session, select(Item), limit=0)
    with pytest.raises(ValueError, match="offset must be"):
        await paginate_offset(session, select(Item), offset=-1)


# --- cursor pagination ----------------------------------------------------


async def test_cursor_pagination_walks_every_row_once(session: AsyncSession) -> None:
    expected = await _seed(session, 25)

    seen: list[Item] = []
    cursor: str | None = None
    for _ in range(10):
        page = await paginate_cursor(
            session, select(Item), key_column=Item.id, limit=7, cursor=cursor
        )
        seen.extend(page.items)
        cursor = page.meta.next_cursor
        if not cursor:
            break

    assert [i.id for i in seen] == [i.id for i in expected]  # no gaps, no repeats


async def test_cursor_is_stable_when_rows_are_inserted(session: AsyncSession) -> None:
    """The reason keyset beats offset: an insert between requests shifts every
    offset, so a reader skips or repeats rows. 'After this key' cannot shift."""
    first_batch = await _seed(session, 10)
    page1 = await paginate_cursor(session, select(Item), key_column=Item.id, limit=5)

    await _seed(session, 5)  # concurrent writes land at the end (UUIDv7)

    page2 = await paginate_cursor(
        session, select(Item), key_column=Item.id, limit=5, cursor=page1.meta.next_cursor
    )
    assert [i.id for i in page2.items] == [i.id for i in first_batch[5:10]]


async def test_cursor_descending_order(session: AsyncSession) -> None:
    expected = await _seed(session, 10)
    page = await paginate_cursor(
        session, select(Item), key_column=Item.id, limit=4, descending=True
    )
    assert [i.id for i in page.items] == [i.id for i in reversed(expected)][:4]


async def test_last_page_has_no_cursor(session: AsyncSession) -> None:
    """A next_cursor on the final page sends clients round one extra empty request."""
    await _seed(session, 4)
    page = await paginate_cursor(session, select(Item), key_column=Item.id, limit=10)
    assert page.meta.next_cursor is None
    assert page.meta.has_more is False


async def test_malformed_cursor_raises_value_error(session: AsyncSession) -> None:
    """Callers map this to a 400 — a client-supplied cursor must not 500."""
    await _seed(session, 2)
    with pytest.raises(ValueError, match="Invalid pagination cursor"):
        await paginate_cursor(session, select(Item), key_column=Item.id, cursor="not-base64!!")

    from pycommon.http.pagination import encode_cursor

    with pytest.raises(ValueError, match="Invalid pagination cursor"):
        await paginate_cursor(
            session, select(Item), key_column=Item.id, cursor=encode_cursor({"wrong": "shape"})
        )
